language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
    - ci
matrix:
  include:
    # gcc-4.9
    - os: linux
      addons:
        apt:
          sources:
            # sudo -E apt-add-repository -y "ppa:george-edison55/precise-backports"
            # sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            # mingw-w64 mingw-w64-x86-64-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
script: sudo -E ./build.sh
