language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
    - ci
matrix:
  include:
    # gcc-4.9
    - os: linux
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
        packages:
          - g++-4.9
          - cmake
          - cmake-data
          # mingw-w64 mingw-w64-x86-64-dev

before_install:
  - eval "${MATRIX_EVAL}"
install:

script: sudo -E ./build.sh
